In [1]:
#Devoir surveillé du semestre 5
#Elève : Irène AMEDJI
#Année scolaire : 2023-2024

In [2]:
############Exercice 1############

In [26]:
#1-a) Oui le graphe est orienté car car la matrice d'adjacence M est symétrique.

# Matrice d'adjacence

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

M = np.array([[0, 1, 1, 1, 0],
              [1, 0, 1, 0, 1],
              [1, 1, 0, 0, 1],
              [0, 1, 0, 0, 1],
              [1, 1, 0, 1, 0]])

def is_oriented(matrix):
    return not np.array_equal(matrix, matrix.T)

oriented = is_oriented(M)
if oriented:
    print("Le graphe est orienté.")
else:
    print("Le graphe n'est pas orienté.")

Le graphe est orienté.


In [39]:
#b- Représentons le graphe G


# La matrice donnée
M = np.array([[0, 1, 1, 1, 0],
              [1, 0, 1, 0, 1],
              [1, 1, 0, 0, 1],
              [0, 1, 0, 0, 1],
              [1, 1, 0, 1, 0]])

# Création du graphe à partir de la matrice
G = nx.from_numpy_matrix(M)

# Définition d'une disposition aléatoire des nœuds
pos = nx.random_layout(G)

# Dessin du graphe
nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=500, font_weight='bold', font_size=10)
plt.title('Graphe à partir de la matrice M')
plt.show()


NetworkXError: random_state_index is incorrect

In [11]:
#c) Ordre du graphe et degré de chaque sommet

order = len(M)
degrees = [sum(row) for row in M]
vertices = ['A', 'B', 'C', 'D', 'E']
for i, vertex in enumerate(vertices):
    print(f"Le degré de {vertex} est {degrees[i]}")
print(f"L'ordre du graphe est {order}")


Le degré de A est 3
Le degré de B est 3
Le degré de C est 3
Le degré de D est 2
Le degré de E est 3
L'ordre du graphe est 5


In [12]:
# 1-d) Trouver les sommets non adjacents

non_adjacent_vertices = []
for i in range(order):
    for j in range(order):
        if M[i][j] == 0 and i != j:
            non_adjacent_vertices.append((vertices[i], vertices[j]))

if non_adjacent_vertices:
    print("Le graphe possède des sommets non adjacents :")
    for pair in non_adjacent_vertices:
        print(f"{pair[0]} et {pair[1]} ne sont pas adjacents.")
else:
    print("Le graphe ne possède pas de sommets non adjacents.")


Le graphe possède des sommets non adjacents :
A et E ne sont pas adjacents.
B et D ne sont pas adjacents.
C et D ne sont pas adjacents.
D et A ne sont pas adjacents.
D et C ne sont pas adjacents.
E et C ne sont pas adjacents.


In [24]:
# 2) Déterminer la matrice M²

# Fonction pour calculer la matrice M²
def calculer_matrice_carree(graph):
    adjacency_matrix = np.array(graph)
    squared_matrix = np.dot(adjacency_matrix, adjacency_matrix)
    return squared_matrix

graph =[
    [0, 1, 1, 1, 0],
    [1, 0, 1, 0, 1],
    [1, 1, 0, 0, 1],
    [0, 1, 0, 0, 1],
    [1, 1, 0, 1, 0]
]

# Calcul de la matrice M² du graphe donné
matrice_carree = calculer_matrice_carree(graph)

# Affichage de la matrice M²
print("Matrice M² du graphe :")
print(matrice_carree)


Matrice M² du graphe :
[[2 2 1 0 3]
 [2 3 1 2 1]
 [2 2 2 2 1]
 [2 1 1 1 1]
 [1 2 2 1 2]]


In [15]:
# 2-a) Le nombre de chemins de longueur 2 partant de B

starting_from_B = M_square[1][:]
number_of_paths_starting_B = sum(starting_from_B)
print(f"Le nombre de chemins de longueur 2 partant de B est {number_of_paths_starting_B}")

Le nombre de chemins de longueur 2 partant de B est 9


In [16]:
# 2-b) Le nombre de chemins de longueur 2 arrivant en B
arriving_at_B = M_square[:, 1]
number_of_paths_arriving_B = sum(arriving_at_B)
print(f"Le nombre de chemins de longueur 2 arrivant en B est {number_of_paths_arriving_B}")


Le nombre de chemins de longueur 2 arrivant en B est 10


In [17]:
# 2-c) Trouver un couple (X,Y) où il n'existe pas de chemin de longueur 2 allant de X à Y
no_path_exists = np.where(M_square == 0)
if len(no_path_exists[0]) > 0:
    x = vertices[no_path_exists[0][0]]
    y = vertices[no_path_exists[1][0]]
    print(f"Il n'existe pas de chemin de longueur 2 allant de {x} à {y}.")
else:
    print("Tous les couples (X,Y) ont un chemin de longueur 2.")

Il n'existe pas de chemin de longueur 2 allant de A à D.


In [25]:
#############Exercice2####################

In [40]:
#1- Représentons le graphe

import networkx as nx
import matplotlib.pyplot as plt

# Création du graphe
G = nx.Graph()

# Ajout des nœuds (groupes)
groupes = ['g1', 'g2', 'g3', 'g4', 'g5']
G.add_nodes_from(groupes)

# Ajout des arêtes (liens entre groupes et épreuves)
liens = {
    'g1': ['e1', 'e2', 'e3'],
    'g2': ['e2', 'e3', 'e4', 'e6'],
    'g3': ['e1', 'e3', 'e5'],
    'g4': ['e1', 'e2', 'e4'],
    'g5': ['e2', 'e4', 'e5']
}

for groupe, epreuves in liens.items():
    for epreuve in epreuves:
        G.add_edge(groupe, epreuve)

# Visualisation du graphe
pos = nx.spring_layout(G)  # disposition des nœuds

nx.draw(G, pos, with_labels=True, node_size=800, node_color='skyblue', font_weight='bold')
plt.title('Graphe des épreuves pour les groupes')
plt.show()


NetworkXError: random_state_index is incorrect

In [37]:
#2-Coloriage des graphes

# Attribution des couleurs aux épreuves et aux groupes
couleurs = {
    'e1': 'orange',
    'e2': 'lightgreen',
    'e3': 'lightblue',
    'e4': 'pink',
    'e5': 'yellow',
    'e6': 'violet',
    'g1': 'skyblue',
    'g2': 'salmon',
    'g3': 'lightgray',
    'g4': 'lightcoral',
    'g5': 'lightyellow'
}

# Affichage du graphe avec les couleurs attribuées
nx.draw(G, pos, with_labels=True, node_size=800, node_color=[couleurs[node] for node in G.nodes()], font_weight='bold')
plt.title('Graphe des épreuves pour les groupes avec couleurs')
plt.show()


NameError: name 'pos' is not defined